/**
 * approveProposal (spec §7.3, §10) — callable. The ONLY path that writes to the real Google
 * Calendar, and only after explicit user approval. On approval it:
 *   1. writes the approved blocks to Google Calendar (tagged Orbit-created),
 *   2. creates `events` docs with status `synced`,
 *   3. flips the proposal to `approved`.
 * Reminders for the synced events are then generated by onEventConfirmed once they're confirmed.
 */
import { onCall, HttpsError } from "firebase-functions/v2/https";
import { logger } from "firebase-functions";
import {
  repositories,
  writeBlock,
  type ProposedBlock,
  type CalendarEvent,
} from "@orbit/core";
import {
  GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET,
  GOOGLE_OAUTH_REDIRECT_URI,
} from "./secrets.js";
import { getCalendarCredentials } from "./calendarAuth.js";

interface ApproveProposalData {
  /** YYYY-MM-DD of the proposal being approved. */
  date: string;
  /** Optional subset of block indices the user approved; defaults to all. */
  approvedIndices?: number[];
  /** Optional user edits keyed by block index (start/end overrides). */
  edits?: Record<number, { start?: string; end?: string }>;
}

export const approveProposal = onCall<ApproveProposalData>(
  {
    secrets: [GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET, GOOGLE_OAUTH_REDIRECT_URI],
  },
  async (request) => {
    const uid = request.auth?.uid;
    if (!uid) throw new HttpsError("unauthenticated", "Sign in required.");

    const { date, approvedIndices, edits } = request.data;
    if (!date) throw new HttpsError("invalid-argument", "Missing proposal date.");

    const profile = await repositories.users.getUserProfile(uid);
    if (!profile) throw new HttpsError("not-found", "User profile not found.");

    const proposal = await repositories.proposals.getProposal(uid, date);
    if (!proposal) throw new HttpsError("not-found", `No proposal for ${date}.`);
    if (proposal.status !== "pending") {
      throw new HttpsError("failed-precondition", `Proposal already ${proposal.status}.`);
    }

    const creds = await getCalendarCredentials(uid, profile);
    if (!creds) throw new HttpsError("failed-precondition", "Google Calendar not connected.");

    const selected: { block: ProposedBlock; index: number }[] = proposal.blocks
      .map((block, index) => ({ block, index }))
      .filter(({ index }) => !approvedIndices || approvedIndices.includes(index))
      .map(({ block, index }) => ({
        block: {
          ...block,
          start: edits?.[index]?.start ?? block.start,
          end: edits?.[index]?.end ?? block.end,
        },
        index,
      }));

    const written: string[] = [];
    for (const { block } of selected) {
      const task = await repositories.tasks.getTask(uid, block.taskId);
      const title = task ? `🔵 ${task.title}` : "🔵 Focus block";

      const googleEventId = await writeBlock(creds.refreshToken, creds.calendarId, {
        title,
        start: block.start,
        end: block.end,
      });

      const eventDoc: Omit<CalendarEvent, "id"> = {
        title,
        start: block.start,
        end: block.end,
        source: "orbit",
        googleEventId,
        type: "focus",
        taskId: block.taskId,
        status: "synced",
      };
      const eventId = await repositories.events.createEvent(uid, eventDoc);
      written.push(eventId);
    }

    await repositories.proposals.setProposalStatus(uid, date, "approved");
    logger.info("proposal.approved", { uid, date, count: written.length });

    return { approved: written.length, eventIds: written };
  },
);
